# Use Ubuntu 22.04 as the base image
FROM ubuntu:jammy

# Update and install necessary packages
RUN apt-get update && apt-get install -y \
    gcc \
    g++ \
    git \
    cmake \
    mingw-w64 \
    && rm -rf /var/lib/apt/lists/*

# Set the working directory
WORKDIR /code

# Copy your source code to the container
COPY . .

# Default command or entry point for the container
CMD ["bash"]
